# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gattopuccino < Formula
  desc "GattoPuccino is a command-line tool that takes an image file and applies a coffee-themed color palette to it. It supports four different flavors - latte, frappe, macchiato, and mocha. GattoPuccino uses the ImageMagick cli tool to apply the color palette."
  homepage "https://github.com/DevMentat/GattoPuccino/"
  version "2.7"

  depends_on "imagemagick"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.7/GattoPuccino_2.7_darwin_amd64.tar.gz"
      sha256 "502354dfa203dee0075f58651d694ce6c825997ae28bf02a4eaf93bdb283ded1"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.7/GattoPuccino_2.7_darwin_arm64.tar.gz"
      sha256 "abeb84c67a4da61849ccd90424209f462f25f716ac8110356c6155a53a7ba53e"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.7/GattoPuccino_2.7_linux_arm64.tar.gz"
      sha256 "68f1c1f63634fd772f5f0e863c49adbe727070c3279419d13997856ed9b4b0de"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.7/GattoPuccino_2.7_linux_amd64.tar.gz"
      sha256 "e5cab069ba42eda1bb92c5c75ba27e4a7fcfcffdaf81891398c361ff09883e95"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  def caveats
    <<~EOS
      gattopuccino <flavor> <image> (Flavor available: latte, frappe, macchiato, or mocha)
    EOS
  end
end
