# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gattopuccino < Formula
  desc "GattoPuccino is a command-line tool that takes an image file and applies a coffee-themed color palette to it. It supports four different flavors - latte, frappe, macchiato, and mocha. GattoPuccino uses the ImageMagick cli tool to apply the color palette."
  homepage "https://github.com/DevMentat/GattoPuccino/"
  version "2.6"

  depends_on "imagemagick"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.6/GattoPuccino_2.6_darwin_amd64.tar.gz"
      sha256 "f2bcf117fa727641e13e81c38f2ed821cecbbc63440fb30c36180a6e0ad98d32"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.6/GattoPuccino_2.6_darwin_arm64.tar.gz"
      sha256 "631c507ae96bed1cd9feded0e27184def5debb362d9c826b8505ec99afd01967"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.6/GattoPuccino_2.6_linux_amd64.tar.gz"
      sha256 "6dcf64c298ef52c637f13fa6b57b4fb3f50fe50de457b4aa9e856e28a83f7970"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.6/GattoPuccino_2.6_linux_arm64.tar.gz"
      sha256 "e67649914a195a09a19a93cba23ec914dd9bc6b54f10f2bd73029ee1d58a9210"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  def caveats
    <<~EOS
      gattopuccino <flavor> <image> (Flavor available: latte, frappe, macchiato, or mocha)
    EOS
  end
end
