# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goodgatto < Formula
  desc "GattoPuccino is a command-line tool that takes an image file and applies a coffee-themed color palette to it. It supports four different flavors - latte, frappe, macchiato, and mocha. GattoPuccino uses the ImageMagick cli tool to apply the color palette."
  homepage "https://github.com/DevMentat/GattoPuccino/"
  version "2.3"

  depends_on "imagemagick"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.3/GattoPuccino_2.3_darwin_arm64.tar.gz"
      sha256 "ab87317169aa96ea8a79d2e0d7172466d90db08577bc65af61250c1e261d7b95"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.3/GattoPuccino_2.3_darwin_amd64.tar.gz"
      sha256 "871b971ec94d4edc12e6e48f393a0c7a850aa1108c33f45d1ef0c69e0b79c118"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.3/GattoPuccino_2.3_linux_arm64.tar.gz"
      sha256 "a7244abb87c53a681d8bb09a6b3652ed32586e2e0cbc7874fe1c29cb6e83e98a"

      def install
        bin.install "GattoPuccino"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v2.3/GattoPuccino_2.3_linux_amd64.tar.gz"
      sha256 "05eb059b04a1a16c1e7c6389faec5db518e8521694d8e48f64b6ee7abe64067a"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  def caveats
    <<~EOS
      gattopuccino <flavor> <image> (Flavor available: latte, frappe, macchiato, or mocha)
    EOS
  end
end
